name: "Test Checkout"

on: ["push"]

jobs:
  checkout-self-repo:
    runs-on: ubuntu-latest
    steps:
      - name: List before checkout
        run: ls -l
      - name: checkout
        uses: action/checkout@v4
      - name: List after checkout
        run: ls -l