name: "Context"

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "My Step"
        env:
          MY_ACTION: ${{ github.action }}
        run: echo "Hello, $MY_ACTION"